### ISSUE TITLE
AWS OpenSearch Integration testing.

### ISSUE THREAD

**Issue by niedbalski** [fluent/fluent-bit-ci#39]
## Description

This issue tracks the implementation of integration testing on top of the new out_opensearch plugin implementation.

1.9.0-rc4 implements out_opensearch https://github.com/fluent/fluent-bit/commit/6fdaa9e3a94fab9039e977b3d7477dbf9ab06b21 

The testing matrix that will be initially supported is:

Fluent-bit | EKS Version | Event | OpenSearch Release
-- | -- | -- | --
master | 1.21 | Push to master / PR to plugin | Nightly build, latest release
master | 1.20 | Push to master  / PR to plugin | Nightly build, latest release
master | 1.19 | Push to master  / PR to plugin | Nightly build, latest release
1.9 | 1.21 | Push to 1.9 branch / PR to branch | Nightly build, latest release
1.9 | 1.20 | Push to 1.9 branch / PR to branch | Nightly build, latest release
1.9 | 1.19 | Push to 1.9 branch / PR to branch | Nightly build, latest release

The components to be used and implemented are:

1. OpenSearch helm chart https://opensearch.org/docs/latest/opensearch/install/helm/ , Implement a basic validation test based on the ElasticSearch test https://github.com/calyptia/fluent-bit-ci/tree/main/integration/tests/elasticsearch

2. For the AWS hosted version (https://aws.amazon.com/opensearch-service/features/), the following
is the cluster type matrix supported.

Cluster type | Master node type | Data node type
-- | -- | --
Dedicated master node | 1 x m5.large.search or m6g.large.search | 1 x >= M5

## Tasks 

- [X] Create an independent AWS account that has a billing account associated.
- [X] Associate a new IAM role that allows access to OpenSearch and EC2
- [X] Add the AWS credentials to the infra repository and configure the AWS provider
- [X] Add the terraform resources to handle the 3 Kubernetes cluster types according to the following specs:
- [X] Add the terraform resources https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain
to create an OpenSearch index/cluster.
- [X] Implement the integration test that uses the versions outlined on the spec.

## Further Notes

N/A

**Comment by niedbalski** [comment]
All tasks have been completed, I am closing this issue as no further work has to be performed.
